--
-- PostgreSQL database dump
--

\restrict v2OQbVSXRepWYdEjcQLdWyxSHT53irDRK5RFK2jb4wB17fSuly5DYREHJ1UWzbg

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-10-03 14:39:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 25015)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 25014)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 25023)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 25022)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 25009)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 25008)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 25029)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 25037)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 25036)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 25028)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 25043)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 25042)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 25101)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 25100)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 25001)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 25000)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 24993)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 24992)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 25249)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 25130)
-- Name: negocio_aperitivo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.negocio_aperitivo (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    precio numeric(10,2) NOT NULL
);


ALTER TABLE public.negocio_aperitivo OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 25129)
-- Name: negocio_aperitivo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.negocio_aperitivo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negocio_aperitivo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 25178)
-- Name: negocio_cita; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.negocio_cita (
    id bigint NOT NULL,
    fecha_hora date NOT NULL,
    hora time without time zone NOT NULL,
    estado character varying(4) NOT NULL,
    notas text,
    saldo_pend numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    colaborador_id bigint NOT NULL,
    paciente_id bigint NOT NULL,
    servicio_id bigint NOT NULL
);


ALTER TABLE public.negocio_cita OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 25186)
-- Name: negocio_cita_aperitivos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.negocio_cita_aperitivos (
    id bigint NOT NULL,
    cita_id bigint NOT NULL,
    aperitivo_id bigint NOT NULL
);


ALTER TABLE public.negocio_cita_aperitivos OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 25185)
-- Name: negocio_cita_aperitivos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.negocio_cita_aperitivos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negocio_cita_aperitivos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 25177)
-- Name: negocio_cita_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.negocio_cita ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negocio_cita_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 25136)
-- Name: negocio_colaborador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.negocio_colaborador (
    id bigint NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    tipo_documento character varying(2) NOT NULL,
    numero_documento character varying(10) NOT NULL,
    celular character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.negocio_colaborador OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 25135)
-- Name: negocio_colaborador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.negocio_colaborador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negocio_colaborador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 25168)
-- Name: negocio_historiaclinica; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.negocio_historiaclinica (
    id bigint NOT NULL,
    observaciones text,
    recomendaciones text,
    created_at timestamp with time zone NOT NULL,
    paciente_id bigint NOT NULL
);


ALTER TABLE public.negocio_historiaclinica OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 25167)
-- Name: negocio_historiaclinica_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.negocio_historiaclinica ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negocio_historiaclinica_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 25144)
-- Name: negocio_paciente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.negocio_paciente (
    id bigint NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    tipo_documento character varying(2),
    etiquetas_pac character varying(3),
    numero_documento character varying(10),
    celular character varying(20) NOT NULL,
    direccion character varying(100),
    fecha_nacimiento date,
    emergencia_nombre character varying(500),
    emergencia_number character varying(10),
    condiciones_medicas text,
    alergias text,
    created_at timestamp with time zone NOT NULL,
    extras text
);


ALTER TABLE public.negocio_paciente OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 25143)
-- Name: negocio_paciente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.negocio_paciente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negocio_paciente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 25152)
-- Name: negocio_servicio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.negocio_servicio (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    duracion integer NOT NULL,
    precio numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT negocio_servicio_duracion_check CHECK ((duracion >= 0))
);


ALTER TABLE public.negocio_servicio OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 25151)
-- Name: negocio_servicio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.negocio_servicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negocio_servicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 25192)
-- Name: negocio_servicio_tratamientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.negocio_servicio_tratamientos (
    id bigint NOT NULL,
    servicio_id bigint NOT NULL,
    tratamiento_id bigint NOT NULL
);


ALTER TABLE public.negocio_servicio_tratamientos OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 25191)
-- Name: negocio_servicio_tratamientos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.negocio_servicio_tratamientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negocio_servicio_tratamientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 25159)
-- Name: negocio_tratamiento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.negocio_tratamiento (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.negocio_tratamiento OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 25158)
-- Name: negocio_tratamiento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.negocio_tratamiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negocio_tratamiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5083 (class 0 OID 25015)
-- Dependencies: 224
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5085 (class 0 OID 25023)
-- Dependencies: 226
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5081 (class 0 OID 25009)
-- Dependencies: 222
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add aperitivo	7	add_aperitivo
26	Can change aperitivo	7	change_aperitivo
27	Can delete aperitivo	7	delete_aperitivo
28	Can view aperitivo	7	view_aperitivo
29	Can add colaborador	8	add_colaborador
30	Can change colaborador	8	change_colaborador
31	Can delete colaborador	8	delete_colaborador
32	Can view colaborador	8	view_colaborador
33	Can add paciente	9	add_paciente
34	Can change paciente	9	change_paciente
35	Can delete paciente	9	delete_paciente
36	Can view paciente	9	view_paciente
37	Can add servicio	10	add_servicio
38	Can change servicio	10	change_servicio
39	Can delete servicio	10	delete_servicio
40	Can view servicio	10	view_servicio
41	Can add tratamiento	11	add_tratamiento
42	Can change tratamiento	11	change_tratamiento
43	Can delete tratamiento	11	delete_tratamiento
44	Can view tratamiento	11	view_tratamiento
45	Can add historia clinica	12	add_historiaclinica
46	Can change historia clinica	12	change_historiaclinica
47	Can delete historia clinica	12	delete_historiaclinica
48	Can view historia clinica	12	view_historiaclinica
49	Can add cita	13	add_cita
50	Can change cita	13	change_cita
51	Can delete cita	13	delete_cita
52	Can view cita	13	view_cita
\.


--
-- TOC entry 5087 (class 0 OID 25029)
-- Dependencies: 228
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- TOC entry 5089 (class 0 OID 25037)
-- Dependencies: 230
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5091 (class 0 OID 25043)
-- Dependencies: 232
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5093 (class 0 OID 25101)
-- Dependencies: 234
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5079 (class 0 OID 25001)
-- Dependencies: 220
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	negocio	aperitivo
8	negocio	colaborador
9	negocio	paciente
10	negocio	servicio
11	negocio	tratamiento
12	negocio	historiaclinica
13	negocio	cita
\.


--
-- TOC entry 5077 (class 0 OID 24993)
-- Dependencies: 218
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-08-23 07:18:51.397764-05
2	auth	0001_initial	2025-08-23 07:18:51.469823-05
3	admin	0001_initial	2025-08-23 07:18:51.49083-05
4	admin	0002_logentry_remove_auto_add	2025-08-23 07:18:51.496871-05
5	admin	0003_logentry_add_action_flag_choices	2025-08-23 07:18:51.503874-05
6	contenttypes	0002_remove_content_type_name	2025-08-23 07:18:51.514874-05
7	auth	0002_alter_permission_name_max_length	2025-08-23 07:18:51.521875-05
8	auth	0003_alter_user_email_max_length	2025-08-23 07:18:51.526874-05
9	auth	0004_alter_user_username_opts	2025-08-23 07:18:51.531876-05
10	auth	0005_alter_user_last_login_null	2025-08-23 07:18:51.538874-05
11	auth	0006_require_contenttypes_0002	2025-08-23 07:18:51.540875-05
12	auth	0007_alter_validators_add_error_messages	2025-08-23 07:18:51.545874-05
13	auth	0008_alter_user_username_max_length	2025-08-23 07:18:51.558875-05
14	auth	0009_alter_user_last_name_max_length	2025-08-23 07:18:51.564888-05
15	auth	0010_alter_group_name_max_length	2025-08-23 07:18:51.573887-05
16	auth	0011_update_proxy_permissions	2025-08-23 07:18:51.579899-05
17	auth	0012_alter_user_first_name_max_length	2025-08-23 07:18:51.588398-05
18	negocio	0001_initial	2025-08-23 07:18:51.669196-05
19	negocio	0002_rename_etiquitas_pac_paciente_etiquetas_pac	2025-08-23 07:18:51.675191-05
20	negocio	0003_remove_tratamiento_descripcion_and_more	2025-08-23 07:18:51.684207-05
21	sessions	0001_initial	2025-08-23 07:18:51.695193-05
\.


--
-- TOC entry 5112 (class 0 OID 25249)
-- Dependencies: 253
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- TOC entry 5095 (class 0 OID 25130)
-- Dependencies: 236
-- Data for Name: negocio_aperitivo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.negocio_aperitivo (id, nombre, precio) FROM stdin;
1	Ensalada de Frutas	15000.00
\.


--
-- TOC entry 5107 (class 0 OID 25178)
-- Dependencies: 248
-- Data for Name: negocio_cita; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.negocio_cita (id, fecha_hora, hora, estado, notas, saldo_pend, created_at, colaborador_id, paciente_id, servicio_id) FROM stdin;
\.


--
-- TOC entry 5109 (class 0 OID 25186)
-- Dependencies: 250
-- Data for Name: negocio_cita_aperitivos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.negocio_cita_aperitivos (id, cita_id, aperitivo_id) FROM stdin;
\.


--
-- TOC entry 5097 (class 0 OID 25136)
-- Dependencies: 238
-- Data for Name: negocio_colaborador; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.negocio_colaborador (id, nombres, apellidos, tipo_documento, numero_documento, celular, created_at) FROM stdin;
1	David	Zapata	CC	1006746283	3046330980	2025-09-23 09:14:08.996532-05
\.


--
-- TOC entry 5105 (class 0 OID 25168)
-- Dependencies: 246
-- Data for Name: negocio_historiaclinica; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.negocio_historiaclinica (id, observaciones, recomendaciones, created_at, paciente_id) FROM stdin;
\.


--
-- TOC entry 5099 (class 0 OID 25144)
-- Dependencies: 240
-- Data for Name: negocio_paciente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.negocio_paciente (id, nombres, apellidos, tipo_documento, etiquetas_pac, numero_documento, celular, direccion, fecha_nacimiento, emergencia_nombre, emergencia_number, condiciones_medicas, alergias, created_at, extras) FROM stdin;
4	Paula	Lopez	CC	ANT	0000000000	3012104762		2000-01-01					2025-07-30 14:42:26.543108-05	\N
5	Leidy	Yurani	CC	ANT	0000000000	3125024475		2000-01-01					2025-07-30 14:43:46.696036-05	\N
6	Sra	Sorany	CC	ANT	0000000000	3134148586		1990-01-01					2025-07-30 14:44:46.958221-05	\N
7	Cliente	Medisalud	CC	ANT	0000000000	3184492757		2025-01-01					2025-07-30 14:46:28.454581-05	\N
8	Sra.	Blanca	CC	ANT	0000000000	3142229731		2000-01-01					2025-07-30 14:48:08.588796-05	\N
9	Lady	Jhoana	CC	ANT	0000000000	3178864410		2000-01-01					2025-07-30 14:51:10.438179-05	\N
10	Silvia Fernanda	Rojas	CC	ANT	0000000000	3167319949		2000-01-01					2025-07-30 14:54:00.548483-05	\N
11	Monica	Bohorquez	CC	ANT	0000000000	3188924918		2000-01-01					2025-07-30 14:55:53.259749-05	\N
12	Martha	Jaimes	CC	ANT	0000000000	3003776988		2000-01-01					2025-07-30 14:57:21.160016-05	\N
13	Cliente	Jenisita	CC	ANT	0000000000	3115776165		2000-01-01					2025-07-30 14:58:32.499542-05	\N
14	Viviana	Rodriguez	CC	ANT	0000000000	3204714202		2000-01-01					2025-07-30 15:01:38.434835-05	\N
15	Linda	Salazar	CC	ANT	0000000000	3202634113		2000-01-01					2025-07-30 15:03:09.177813-05	\N
16	Rubiela	Garcia	CC	ANT	0000000000	3115906987		2000-01-01					2025-07-30 15:03:53.792862-05	\N
17	Sandra Milena	Siza	CC	ANT	0000000000	3222496990		2000-01-01					2025-07-30 15:04:40.337224-05	\N
18	Liliana	Serrato	CC	ANT	0000000000	3174242858		2000-01-01					2025-07-30 15:05:27.416642-05	\N
19	Cliente	Vivianita	CC	ANT	0000000000	3174592586		2000-01-01					2025-07-30 15:06:23.808524-05	\N
20	Cliente	Myrian	CC	ANT	0000000000	3007242523		2000-01-01					2025-07-30 15:07:34.168488-05	\N
21	Angelica	Mendez	CC	ANT	0000000000	3184691501		2000-01-01					2025-07-30 15:09:46.032879-05	\N
23	Elizabeth	Tto	CC	ANT	0000000000	3163951243		2000-01-01					2025-07-30 15:19:49.02233-05	\N
24	Natalia	Viola	CC	ANT	0000000000	3162793351		2000-01-01					2025-07-30 15:20:38.580762-05	\N
25	Diana	Lancheros	CC	ANT	0000000000	3159288692		2000-01-01					2025-07-30 15:21:40.716849-05	\N
26	Cliente	Liliana	CC	ANT	0000000000	3163338701		2000-01-01					2025-07-30 15:22:21.8236-05	\N
27	Anyela	Garcia	CC	ANT	0000000000	3165038493		2000-01-01					2025-07-30 15:28:04.138519-05	\N
28	Ingrid	Serrano	CC	ANT	0000000000	3145912096		2000-01-01					2025-07-30 15:29:26.059851-05	\N
29	Meiby	Cala	CC	ANT	0000000000	3156623332		2000-01-01					2025-07-30 15:30:58.3969-05	\N
30	Monica	Lara	CC	ANT	0000000000	3143917441		2000-01-01					2025-07-30 15:31:46.377752-05	\N
31	Profe	Sandra	CC	ANT	0000000000	3132488755		2000-01-01					2025-07-30 15:32:53.161922-05	\N
32	Ginna	Higuera	CC	ANT	0000000000	3160425040		2000-01-01					2025-07-30 15:34:53.511801-05	\N
33	Cliente	Bianca	CC	ANT	0000000000	3177373727		2000-01-01					2025-07-30 15:36:07.097015-05	\N
34	Claudia	Rincon	CC	ANT	0000000000	3008449033		2000-01-01					2025-07-30 15:36:49.249026-05	\N
35	Kelly	Moreno	CC	ANT	0000000000	3209463188		2000-01-01					2025-07-30 15:37:40.305005-05	\N
36	Stefany	De	CC	ANT	0000000000	3114500038		2000-01-01					2025-07-30 15:38:25.658134-05	\N
37	Cliente	Laurita	CC	ANT	0000000000	3182714954		2000-01-01					2025-07-30 15:39:37.624434-05	\N
38	Monica	Gomez	CC	ANT	0000000000	3177851555		2000-01-01					2025-07-30 15:42:18.191891-05	\N
39	Yesica	Barbosa	CC	ANT	0000000000	3175183845		2000-01-01					2025-07-30 15:43:04.607486-05	\N
40	Erika	Olarte	CC	ANT	0000000000	3183384728		2000-01-01					2025-07-30 15:43:46.599127-05	\N
41	Diana	Instructora	CC	ANT	0000000000	3134707867		2000-01-01					2025-07-30 15:47:06.13578-05	\N
42	Carmen	Hernandez	CC	ANT	0000000000	3118700885		2000-01-01					2025-07-30 15:50:02.686415-05	\N
43	Luz Stella	Acosta	CC	ANT	0000000000	3167457255		2000-01-01					2025-07-30 15:51:42.581446-05	\N
44	Laurita	Sandoval	CC	ANT	0000000000	3142995923		2000-01-01					2025-07-30 15:55:01.780306-05	\N
45	Mercy	Mendez	CC	ANT	0000000000	3102949653		2000-01-01					2025-07-30 16:00:25.138453-05	\N
46	Esperanza	Aguillon	CC	ANT	0000000000	3153078635		2000-01-01					2025-07-30 16:01:38.732084-05	\N
47	Yecenia	Villaf	CC	ANT	0000000000	3168909980		2000-01-01					2025-07-30 16:04:05.115229-05	\N
48	Tatiana	Ortirz	CC	ANT	0000000000	3046578647		2000-01-01					2025-07-30 16:05:22.121129-05	\N
49	Cesia	Lucina	CC	ANT	0000000000	3168320540		2000-01-01					2025-07-30 16:06:23.890723-05	\N
50	Saidy	Becerra	CC	ANT	0000000000	3112074918		2000-01-01					2025-07-30 16:09:13.480862-05	\N
51	Sayda	PatiÃ±o	CC	ANT	0000000000	3154779324		2000-01-01					2025-07-30 16:10:33.640739-05	\N
52	Sra.	Maite	CC	ANT	0000000000	3177150734		2000-01-01					2025-07-30 16:11:24.463589-05	\N
53	Magnolia	Quesada	CC	ANT	0000000000	3012205285		2000-01-01					2025-07-30 16:12:24.128972-05	\N
54	Profe	Martha	CC	ANT	0000000000	3125835911		2000-01-01					2025-07-30 16:18:56.574117-05	\N
55	Maritza	Alvarez	CC	ANT	0000000000	3125848627		2000-01-01					2025-07-30 16:19:39.982476-05	\N
56	Yurley	Gomez	CC	ANT	0000000000	3176591937		2003-01-01					2025-07-30 16:20:30.494354-05	\N
57	Diana	Rocio	CC	ANT	0000000000	3115010164		2000-01-01					2025-07-30 16:21:48.366311-05	\N
58	Maira	Escalona	CC	ANT	0000000000	3145363642		2000-01-01					2025-07-30 16:22:37.957866-05	\N
59	Maria	ConcepciÃ³n	CC	ANT	0000000000	3125014001		2000-01-01					2025-07-30 16:23:15.549874-05	\N
60	Sra Yanet	Familiar Nancy	CC	ANT	0000000000	3214047159		2000-01-01					2025-07-30 16:24:08.973224-05	\N
61	Deisy	Bermudez	CC	ANT	0000000000	3005669949		2003-01-01					2025-07-30 16:24:56.334028-05	\N
62	Leidy	Badillo	CC	ANT	0000000000	3163542599		2000-01-01					2025-07-30 16:25:51.476916-05	\N
63	Andreita	UÃ±as	CC	ANT	0000000000	3156261699		2000-01-01					2025-07-30 16:26:30.964628-05	\N
64	Carlos	Rey	CC	ANT	0000000000	3165324100		2000-01-01					2025-07-30 16:27:21.22803-05	\N
65	Yuli	Barrera	CC	ANT	0000000000	3182669226		2000-01-01					2025-07-30 16:28:28.076967-05	\N
66	Fanny	PeÃ±a	CC	ANT	0000000000	3155438489		2000-01-02					2025-07-30 16:29:12.003986-05	\N
67	Carmen	Parra	CC	ANT	0000000000	3173061030		2000-01-01					2025-07-30 16:29:51.763064-05	\N
68	Sra Mirian	Mama Lucho	CC	ANT	0000000000	3176758428		2000-01-01					2025-07-30 16:30:49.867234-05	\N
69	Karen	Caceres	CC	ANT	0000000000	3162416079		2000-01-01					2025-07-30 16:31:28.618532-05	\N
70	Beatriz	Caceres	CC	ANT	0000000000	3185568218		2000-01-01					2025-07-30 16:32:06.339507-05	\N
71	Dary	Jazmin	CC	ANT	0000000000	3203917299		2000-01-01					2025-07-30 16:32:55.738557-05	\N
72	Sandra	Velasquez	CC	ANT	0000000000	3042621381		2000-01-01					2025-07-30 16:33:48.68378-05	\N
73	Elsida	Lopez	CC	ANT	0000000000	3222049286		2000-01-01					2025-07-30 16:35:50.297802-05	\N
74	Juan	Diaz	CC	ANT	0000000000	3116325008		2000-01-01					2025-07-30 16:42:52.142686-05	\N
75	Sandra Milena	Sanchez	CC	ANT	0000000000	3123975578		2000-01-01					2025-07-30 16:44:09.801125-05	\N
76	Liliana	Sanchez	CC	ANT	0000000000	3177664595		2000-01-01					2025-07-30 16:44:49.632705-05	\N
2	Lizeth	Diaz	CC	ANT	0000000000	3162452493		2000-01-01					2025-07-29 22:24:02.369173-05	Hola
3	Nelly	Correa	CC	ANT	0000000000	3218987676		2000-01-01					2025-07-30 14:41:33.721298-05	aaaaaaa
77	Edith	Garcia	CC	ANT	0000000000	3108685964		2000-01-01					2025-07-30 16:45:31.471243-05	\N
78	Sandra	Benavidez	CC	ANT	0000000000	3156461006		2000-01-01					2025-07-30 16:46:48.727303-05	\N
79	Michell	Suarez	CC	ANT	0000000000	3204689406		2000-01-01					2025-07-30 16:48:16.207955-05	\N
80	Aurelia	NiÃ±o	CC	ANT	0000000000	3165335768		2000-01-01					2025-07-30 16:49:27.408072-05	\N
81	Tifany	Nuevo	CC	ANT	0000000000	3011504470		2000-01-01					2025-07-30 16:50:09.263437-05	\N
82	Maria Adela	Ravelo	CC	ANT	0000000000	3162374021		2000-01-01					2025-07-30 16:50:56.799125-05	\N
83	Julieth	Rojas	CC	ANT	0000000000	3152073354		2000-01-01					2025-07-30 16:51:25.950044-05	\N
84	Tatiana	Celis	CC	ANT	0000000000	3165384462		2000-01-01					2025-07-30 16:51:57.622055-05	\N
85	Claudia	Pereira	CC	ANT	0000000000	3164751925		2000-01-01					2025-07-30 16:52:30.58186-05	\N
86	Miguel	Velazquez	CC	ANT	0000000000	3144908141		2000-01-01					2025-07-30 16:53:04.629536-05	\N
87	Sra Luz	Mery	CC	ANT	0000000000	3015362167		2000-01-01					2025-07-30 16:53:36.373675-05	\N
88	Marlene	Guerrero	CC	ANT	0000000000	3012349514		2003-01-01					2025-07-30 16:54:10.301508-05	\N
89	Isabela	Serrano	CC	ANT	0000000000	3042137173		2003-01-01					2025-07-30 16:55:04.277816-05	\N
90	Silena	AcuÃ±a	CC	ANT	0000000000	3136364634		2000-01-01					2025-07-30 16:55:35.853005-05	\N
91	Lesly	GutiÃ©rrez	CC	ANT	0000000000	3177697645		2000-01-01					2025-07-30 16:56:18.173191-05	\N
92	Paola	Gomez	CC	ANT	0000000000	3152466170		2000-01-01					2025-07-30 16:57:03.91678-05	\N
93	Nelly	Vesga	CC	ANT	0000000000	3132754948		2003-01-01					2025-07-30 16:57:38.731643-05	\N
94	Yuly	Andrea	CC	ANT	0000000000	3143123649		2000-01-01					2025-07-30 16:58:14.877692-05	\N
95	Sharon	Anaya	CC	ANT	0000000000	3228413911		2000-01-01					2025-07-30 17:00:00.812696-05	\N
96	Tatiana	ChanagÃ¡	CC	ANT	0000000000	3023389360		2000-01-01					2025-07-30 17:00:35.58862-05	\N
97	Sra	Angela	CC	ANT	0000000000	3151007788		2003-01-01					2025-07-30 17:01:56.81246-05	\N
98	Adriana	Lizcano	CC	ANT	0000000000	3112656520		2000-01-01					2025-07-30 17:02:45.821577-05	\N
99	Sandra	Sanchez	CC	ANT	0000000000	3053158751		2000-01-01					2025-07-30 17:09:14.275676-05	\N
100	Mayra	Cano Moreno	CC	ANT	0000000000	3143942263		2000-01-01					2025-07-30 17:10:06.569889-05	\N
101	Viviana	Lozada	CC	ANT	0000000000	3163751758		2003-01-01					2025-07-30 17:10:44.344934-05	\N
102	Blanca	De Serrano	CC	ANT	0000000000	3102926264		2000-01-01					2025-07-30 17:11:47.344894-05	\N
103	Leidy	Rodriguez	CC	ANT	0000000000	3163603885		2003-01-01					2025-07-30 17:12:46.128659-05	\N
104	Sra	Berenice	CC	ANT	0000000000	3184763238		2000-01-01					2025-07-30 17:13:19.888978-05	\N
105	Jenifer	hija De Olga	CC	ANT	0000000000	3156086578		2000-01-01					2025-07-30 17:14:37.161284-05	\N
106	DoÃ±a Angelica	LÃ­nea	CC	ANT	0000000000	3134730640		2003-01-01					2025-07-30 17:15:16.7061-05	\N
107	Katerin	Reductores	CC	ANT	0000000000	3142093298		2000-01-01					2025-07-30 17:15:56.288303-05	\N
108	Liliana	Rueda	CC	ANT	0000000000	3175768877		2003-01-01					2025-07-30 17:16:33.343492-05	\N
109	Isabel	Villamizar	CC	ANT	0000000000	3177263798		2003-01-01					2025-07-30 17:17:28.048598-05	\N
110	Erika	Camacho	CC	ANT	0000000000	3166981551		2000-01-01					2025-07-30 17:18:08.783501-05	\N
111	Elsa	Rivera	CC	ANT	0000000000	3176073889		2000-01-01					2025-07-30 17:19:22.655947-05	\N
112	Dennis	RamÃ­rez	CC	ANT	0000000000	3177562799		2000-01-01					2025-07-30 17:20:05.21434-05	\N
113	Merly	Ortiz	CC	ANT	0000000000	3213741611		2000-01-01					2025-07-30 17:20:43.847527-05	\N
114	Paula	Paula	CC	ANT	0000000000	3165374873		2000-01-01					2025-07-30 17:21:33.054353-05	\N
115	Liseth	Torres	CC	ANT	0000000000	3052794373		2000-01-01					2025-07-30 17:22:13.230734-05	\N
116	Zareth Daniela	Tto	CC	ANT	0000000000	3185402347		2000-01-01					2025-07-30 17:22:54.693712-05	\N
117	Angi	Love	CC	ANT	0000000000	3214923233		2000-01-01					2025-07-30 17:23:52.559323-05	\N
118	Ruth	Arcila	CC	ANT	0000000000	3163293213		2000-01-01					2025-07-30 17:24:54.472972-05	\N
119	Kamila	Castro	CC	ANT	0000000000	34642764964		2000-01-01					2025-07-30 20:41:08.788703-05	\N
120	Daniela	Ardila	CC	ANT	0000000000	321 8263452		2000-01-01					2025-07-30 20:42:47.047633-05	\N
121	Alejandra	Giraldo Esparza	CC	ANT	0000000000	300 1536594		2000-01-01					2025-07-30 20:45:32.359905-05	\N
122	Leidy	Galvis	CC	ANT	0000000000	310 6612053		2000-01-01					2025-07-30 20:46:03.398394-05	\N
123	Adriana	Bonilla	CC	ANT	0000000000	317 3441178		2000-01-01					2025-07-30 20:46:46.246785-05	\N
124	Paola	Quintero	CC	ANT	0000000000	304 3479690		2000-01-01					2025-07-30 20:47:17.766405-05	\N
125	Liliana	Barragan	CC	ANT	0000000000	310 5862503		2000-01-01					2025-07-30 20:47:51.0617-05	\N
126	Juliana	Villalobos	CC	ANT	0000000000	310 6195763		2000-01-01					2025-07-30 20:48:31.279788-05	\N
127	Miguel	Xx	CC	ANT	0000000000	312 3931856		2000-01-01					2025-07-30 20:54:47.637502-05	\N
128	Madrina	Rosalba	CC	ANT	0000000000	311 5154799		2000-01-01					2025-07-30 20:55:19.332492-05	\N
129	Claudia	Navarro	CC	ANT	0000000000	316 6991183		2000-01-01					2025-07-30 20:56:13.692798-05	\N
130	Cliente	Sinsi	CC	ANT	0000000000	323 2511728		2000-01-02					2025-07-30 20:57:25.06796-05	\N
131	Yuli	Diaz	CC	ANT	0000000000	312 4276904		2000-01-01					2025-07-30 20:57:57.123848-05	\N
132	Yagixa	Pereira	CC	ANT	0000000000	318 6312377		2000-01-01					2025-07-30 20:58:33.835279-05	\N
133	Ludy	Mesa	CC	ANT	0000000000	300 7893917		2000-01-01					2025-07-30 20:59:09.004549-05	\N
134	Cliente	Pao	CC	ANT	0000000000	302 5441311		2000-01-01					2025-07-30 21:00:39.740184-05	\N
135	Jonathan	Suarez	CC	ANT	0000000000	311 4994509		2000-01-01					2025-07-30 21:02:54.063559-05	\N
136	AngÃ©lica	Duarte	CC	ANT	0000000000	317 7551533		2000-01-01					2025-07-30 21:04:10.868042-05	\N
137	Alejandra	Garcia	CC	ANT	0000000000	315 0589504		2000-01-01					2025-07-30 21:04:41.564818-05	\N
138	Elena Amiga	De Ana	CC	ANT	0000000000	301 3123134		2000-01-01					2025-07-30 21:05:12.865988-05	\N
139	Karen	Cordoba	CC	ANT	0000000000	321 3191995		2000-01-01					2025-07-30 21:05:41.545836-05	\N
140	Iveth	Jhoana	CC	ANT	0000000000	320 4007196		2000-01-01					2025-07-30 21:06:12.953025-05	\N
141	Daybely	Isac	CC	ANT	0000000000	302 4526515		2000-01-01					2025-07-30 21:06:41.71364-05	\N
142	Santiago	Quesada	CC	ANT	0000000000	313 4157961		2000-01-01					2025-07-30 21:07:18.729513-05	\N
143	Rodrigo	Navarro	CC	ANT	0000000000	300 2959439		2000-01-01					2025-07-30 21:12:50.723276-05	\N
144	Sra	Angi	CC	ANT	0000000000	323 3243343		2003-01-01					2025-07-30 21:13:39.26025-05	\N
145	Graciela	Rueda	CC	ANT	0000000000	312 4707063		2000-01-01					2025-07-30 21:14:10.936207-05	\N
146	Claudia	Villamizar	CC	ANT	0000000000	302 5157160		2000-01-01					2025-07-30 21:14:41.98378-05	\N
147	Vanesa	Ramirez	CC	ANT	0000000000	318 8105297		2000-01-01					2025-07-30 21:15:19.143482-05	\N
148	Monica	Arse	CC	ANT	0000000000	310 8103814		2000-01-01					2025-07-30 21:15:49.511664-05	\N
149	Mireya	Rubio	CC	ANT	0000000000	318 6335318		2000-01-01					2025-07-30 21:16:22.351842-05	\N
150	Katherin	Davila	CC	ANT	0000000000	305 4666546		2000-10-10					2025-07-30 21:16:58.877168-05	\N
151	Dayana	Vanegas	CC	ANT	0000000000	321 2325164		2000-01-01					2025-07-30 21:18:07.511781-05	\N
152	Viviana	Silva	CC	ANT	0000000000	+1 6173020230		2000-01-01					2025-07-30 21:22:07.357243-05	\N
153	Monica	Gamboa	CC	ANT	0000000000	316 0448738		2000-01-01					2025-07-30 21:22:42.980976-05	\N
154	Xiomara	Delgado	CC	ANT	0000000000	316 0439371		2000-01-01					2025-07-30 21:23:13.044968-05	\N
155	Jeovany	Mejia	CC	ANT	0000000000	313 4010827		2000-01-01					2025-07-30 21:23:47.781332-05	\N
156	Liseth	Beltran	CC	ANT	0000000000	311 4588998		2000-01-01					2025-07-30 21:24:18.380478-05	\N
157	Monica	Guerrero	CC	ANT	0000000000	302 3630461		2000-01-01					2025-07-30 21:25:48.713617-05	\N
158	Yuli	Guevara	CC	ANT	0000000000	323 2251572		2000-01-01					2025-07-30 21:28:27.156193-05	\N
159	Juliana	GÃ³mez	CC	ANT	0000000000	313 2267981		2000-01-01					2025-07-30 21:28:59.218207-05	\N
160	Astrid	Gelvez	CC	ANT	0000000000	310 2663888		2000-01-01					2025-07-30 21:29:34.458912-05	\N
161	Laura	Pedraza	CC	ANT	0000000000	317 6217713		2000-01-01					2025-07-30 21:30:02.090552-05	\N
162	Naila	Ardila	CC	ANT	0000000000	316 6531370		2000-01-01					2025-07-30 21:30:27.786434-05	\N
163	JazmÃ­n	Roa	CC	ANT	0000000000	320 2161651		2000-01-01					2025-07-30 21:30:59.433816-05	\N
164	Alba	Patricia	CC	ANT	0000000000	320 2688834		2000-01-01					2025-07-30 21:31:35.794897-05	\N
165	Alejandra	Leon	CC	ANT	0000000000	301 6333843		2000-01-01					2025-07-30 21:32:05.786584-05	\N
166	Andrea Del Pilar	CaÃ±as	CC	ANT	0000000000	310 8082461		2000-01-01					2025-07-30 21:32:36.722892-05	\N
167	Natalia	Sierra	CC	ANT	0000000000	317 7245786		2000-01-01					2025-07-30 21:33:17.874956-05	\N
168	Andrea	Carrascal	CC	ANT	0000000000	317 7509950		2000-01-01					2025-07-30 21:34:03.058613-05	\N
169	Doris	JimÃ©nez	CC	ANT	0000000000	310 5946633		2000-01-01					2025-07-30 21:34:31.154673-05	\N
170	Xiomara	Pimiento	CC	ANT	0000000000	300 3505741		2000-01-01					2025-07-30 21:35:04.274554-05	\N
171	Emily	Jaimes	CC	ANT	0000000000	313 3589804		2000-01-01					2025-07-30 21:35:35.363376-05	\N
172	Jessica	Henao	CC	ANT	0000000000	315 2601605		2000-01-01					2025-07-30 21:36:43.259142-05	\N
173	DayaNa	Leon-depilacion 2	CC	ANT	0000000000	315 3694009		2000-01-01					2025-07-30 21:37:12.114023-05	\N
174	Nancy	Cano	CC	ANT	0000000000	315 5090324		2000-01-01					2025-07-30 21:37:35.51495-05	\N
175	Jose	Paredes	CC	ANT	0000000000	323 8585750		2000-01-01					2025-07-30 21:38:31.217682-05	\N
176	Jhon	Solano	CC	ANT	0000000000	302 6523902		2000-01-01					2025-07-30 21:39:02.26655-05	\N
177	Sra Nubia	mamÃ¡ Pabon	CC	ANT	0000000000	320 3791254		2000-01-01					2025-07-30 21:39:37.673404-05	\N
178	Linda	Laura	CC	ANT	0000000000	301 6628029		2000-01-01					2025-07-30 21:40:16.56925-05	\N
179	Gloria Ines	LondoÃ±o	CC	ANT	0000000000	316 5323155		2000-01-01					2025-07-30 21:40:47.945125-05	\N
180	Karen	NÃºÃ±ez	CC	ANT	0000000000	317 5001907		2000-01-01					2025-07-30 21:41:25.83299-05	\N
181	Jaiver	David	CC	ANT	0000000000	300 7780447		2000-01-01					2025-07-30 21:41:55.69683-05	\N
182	Sandra M	Hdez	CC	ANT	0000000000	310 2140475		2000-01-01					2025-07-30 21:42:32.600269-05	\N
183	Yuli	Paola	CC	ANT	0000000000	318 7961803		2000-01-01					2025-07-30 21:43:06.528235-05	\N
184	Maryori	Diaz	CC	ANT	0000000000	323 3925429		2000-01-01					2025-07-30 21:55:50.366336-05	\N
185	Elizabeth	Gallo	CC	ANT	0000000000	318 2534297		2000-01-01					2025-07-30 21:56:20.797231-05	\N
186	Shiirley	Saenz	CC	ANT	0000000000	311 2628496		2000-01-01					2025-07-30 21:56:48.052111-05	\N
187	Claudia	FernÃ¡ndez	CC	ANT	0000000000	+49 1521 9387148		2000-01-01					2025-07-30 21:59:58.444771-05	\N
188	Mayerly	Porras 2	CC	ANT	0000000000	301 5878403		2000-01-01					2025-07-30 22:00:25.85247-05	\N
189	Ferney	Vargas	CC	ANT	0000000000	312 3625585		2000-01-01					2025-07-30 22:00:56.3961-05	\N
190	Dayanna	CarreÃ±o	CC	ANT	0000000000	318 5143163		2000-01-01					2025-07-30 22:01:26.380327-05	\N
191	Cliente	Nataly	CC	ANT	0000000000	304 6497079		2000-01-01					2025-07-30 22:01:51.539873-05	\N
192	Litze Dayana	Vasquez	CC	ANT	0000000000	315 4648691		2000-01-01					2025-07-30 22:02:28.747435-05	\N
193	Mariluz	Melgarejo	CC	ANT	0000000000	317 5033565		2000-01-01					2025-07-30 22:02:55.37993-05	\N
194	Diana	Garrido	CC	ANT	0000000000	313 5668375		2000-01-01					2025-07-30 22:03:21.115199-05	\N
195	Juan	Diaz	CC	ANT	0000000000	301 4157534		2000-01-01					2025-07-30 22:03:49.242663-05	\N
196	Eliana	Lizarazo	CC	ANT	0000000000	313 8444406		2000-01-01					2025-07-30 22:04:32.267147-05	\N
197	Omar	Mantilla	CC	ANT	0000000000	318 8011789		2000-01-01					2025-07-30 22:05:43.642894-05	\N
198	Alejandra	Padilla	CC	ANT	0000000000	316 6591973		2000-01-01					2025-07-30 22:06:08.978372-05	\N
199	Jurley	PestaÃ±as	CC	ANT	0000000000	302 5982006		2000-01-01					2025-07-30 22:06:52.275042-05	\N
200	Juliana	Barrios	CC	ANT	0000000000	315 7166921		2000-01-01					2025-07-30 22:07:36.506163-05	\N
201	Henry	Carvajal	CC	ANT	0000000000	316 6719924		2000-01-01					2025-07-30 22:08:52.729997-05	\N
202	Laura	Vera	CC	ANT	0000000000	316 2392571		2000-01-01					2025-07-30 22:09:23.425712-05	\N
203	Pilar	Toloza	CC	ANT	0000000000	314 4859160		2000-01-01					2025-07-30 22:09:54.625863-05	\N
204	Lizeth	Pinto	CC	ANT	0000000000	321 2073785		2000-01-01					2025-07-30 22:10:34.08984-05	\N
205	Karen	Galvis	CC	ANT	0000000000	321 3753785		2000-01-01					2025-07-30 22:11:12.249525-05	\N
206	Laura Lizeht	Ramirez	CC	ANT	0000000000	318 8186931		2000-01-01					2025-07-30 22:11:55.297361-05	\N
207	Jhohanna	Serrano	CC	ANT	0000000000	316 7550338		2000-01-01					2025-07-30 22:12:26.121136-05	\N
208	Zulay	Tatiana	CC	ANT	0000000000	324 4450519		2000-01-01					2025-07-30 22:12:57.681088-05	\N
209	Doris	MasÃ­as	CC	ANT	0000000000	317 7605679		2000-01-01					2025-07-30 22:13:40.457562-05	\N
210	Javier	Regueros	CC	ANT	0000000000	310 3383186		2000-01-01					2025-07-30 22:14:19.208756-05	\N
211	Damaris	Sierra	CC	ANT	0000000000	316 3436729		2000-01-01					2025-07-30 22:14:50.520633-05	\N
212	Monica	Jaimes	CC	ANT	0000000000	316 6601228		2000-01-01					2025-07-30 22:15:24.800616-05	\N
213	Sofhia	Olivero	CC	ANT	0000000000	+58 412-1850501		2000-01-01					2025-07-30 22:15:56.312345-05	\N
214	Daniela	Blanco	CC	ANT	0000000000	318 0928238		2000-01-01					2025-07-30 22:16:28.288519-05	\N
215	Camila	RodrÃ­guez	CC	ANT	0000000000	321 2231958		2000-01-01					2025-07-30 22:17:00.726035-05	\N
216	Erika	Paola	CC	ANT	0000000000	310 3038827		2000-01-01					2025-07-30 22:17:29.599957-05	\N
217	Olga	Lucia	CC	ANT	0000000000	300 5641268		2000-01-01					2025-07-30 22:18:24.16773-05	\N
218	Andrea	Sta L	CC	ANT	0000000000	310 2853552		2000-01-01					2025-07-30 22:20:01.870598-05	\N
219	Natalia	Celemin	CC	ANT	0000000000	322 8960490		2000-01-01					2025-07-30 22:20:28.943654-05	\N
220	Durley	Medina	CC	ANT	0000000000	318 3865354		2000-01-01					2025-07-30 22:21:01.960018-05	\N
221	Juliana	Jaimes MasÃ­as	CC	ANT	0000000000	316 7070315		2000-01-01					2025-07-30 22:21:43.734534-05	\N
222	Elsa Patricia	SuÃ¡rez	CC	ANT	0000000000	302 4413861		2000-01-01					2025-07-30 22:22:25.454741-05	\N
223	Viviana	Conchila	CC	ANT	0000000000	301 3348147		2000-01-01					2025-07-30 22:23:02.630585-05	\N
224	Lina	DomÃ­nguez	CC	ANT	0000000000	323 2437204		2000-01-01					2025-07-30 22:27:09.424882-05	\N
225	Marcela	Baut	CC	ANT	0000000000	316 7247198		2000-01-01					2025-07-30 22:28:23.317241-05	\N
226	Sandra	Suarez	CC	ANT	0000000000	317 6515425		2000-01-01					2025-07-30 22:29:28.05297-05	\N
227	Leidy	Joya	CC	ANT	0000000000	315 7242712		2000-01-01					2025-07-30 22:30:20.516993-05	\N
228	Jackelin	Trejo	CC	ANT	0000000000	318 6899849		2000-01-01					2025-07-30 22:30:55.484398-05	\N
229	Sra	Astrid	CC	ANT	0000000000	300 1929024		2000-01-01					2025-07-30 22:34:13.903666-05	\N
230	Cliente	Maria	CC	ANT	0000000000	313 8364905		2000-01-01					2025-07-30 22:34:51.051641-05	\N
231	Leidis	Manchego	CC	ANT	0000000000	322 8631414		2000-01-01					2025-07-30 22:35:26.747596-05	\N
232	Jhasnaya	Sanchez	CC	ANT	0000000000	310 8591319		2000-01-01					2025-07-30 22:36:22.308247-05	\N
233	Angie	Ortiz	CC	ANT	0000000000	320 9218501		2000-01-01					2025-07-30 22:37:11.147913-05	\N
234	Dayanna	Moreno	CC	ANT	0000000000	314 4091716		2000-01-01					2025-07-30 22:40:22.874213-05	\N
235	Laura	Blanco	CC	ANT	0000000000	316 4459197		2000-01-01					2025-07-30 22:40:52.002106-05	\N
236	Steban	Alejandro	CC	ANT	0000000000	316 6735326		2000-01-01					2025-07-30 22:41:28.698334-05	\N
237	Claudia	EspaÃ±a	CC	ANT	0000000000	+34 608 68 88 72		2000-01-01					2025-07-30 22:42:04.193828-05	\N
238	Edna	Pinto	CC	ANT	0000000000	317 6954970		2000-01-01					2025-07-30 22:43:31.129028-05	\N
239	Yurley	Silva	CC	ANT	0000000000	317 8686227		2000-01-01					2025-07-30 22:44:00.361308-05	\N
240	Julian	Rueda	CC	ANT	0000000000	317 6667962		2000-01-01					2025-07-30 22:45:04.417037-05	\N
241	Claudia	Vargas	CC	ANT	0000000000	315 2330357		2000-01-01					2025-07-30 22:45:58.592774-05	\N
242	Ana	Jaimes	CC	ANT	0000000000	312 3249260		2000-01-01					2025-07-30 22:46:37.456616-05	\N
243	Willmer	Ojeda	CC	ANT	0000000000	324 6040460		2000-01-01					2025-07-30 22:47:07.473567-05	\N
244	Idaly	Jaimes	CC	ANT	0000000000	304 5455079		2000-01-01					2025-07-30 22:47:37.768785-05	\N
245	Lady Andrea	Pinto	CC	ANT	0000000000	316 2886821		2000-01-01					2025-07-30 22:48:02.80935-05	\N
246	Oscar	Delgado	CC	ANT	0000000000	320 2723772		2000-01-01					2025-07-30 22:48:49.576141-05	\N
247	Julian	Bazurto	CC	ANT	0000000000	318 4938125		2000-01-01					2025-07-30 22:49:14.184048-05	\N
248	Fernanda	Quintero	CC	ANT	0000000000	321 4727015		2000-01-01					2025-07-31 02:45:53.103737-05	\N
249	Kelly	Ramirez	CC	ANT	0000000000	319 2588292		2000-01-01					2025-07-31 02:47:30.266565-05	\N
250	David	Zapata	CC	ANT	0000000000	3046330980		2000-01-01					2025-07-31 04:00:08.072305-05	\N
1	Mayerli	Garcia	CC	PPN	1098639051	3186279215		1990-12-26					2025-07-29 21:44:02.125288-05	
\.


--
-- TOC entry 5101 (class 0 OID 25152)
-- Dependencies: 242
-- Data for Name: negocio_servicio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.negocio_servicio (id, nombre, duracion, precio, created_at) FROM stdin;
\.


--
-- TOC entry 5111 (class 0 OID 25192)
-- Dependencies: 252
-- Data for Name: negocio_servicio_tratamientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.negocio_servicio_tratamientos (id, servicio_id, tratamiento_id) FROM stdin;
\.


--
-- TOC entry 5103 (class 0 OID 25159)
-- Dependencies: 244
-- Data for Name: negocio_tratamiento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.negocio_tratamiento (id, nombre) FROM stdin;
\.


--
-- TOC entry 5118 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5119 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5120 (class 0 OID 0)
-- Dependencies: 221
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- TOC entry 5121 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5122 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- TOC entry 5123 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5124 (class 0 OID 0)
-- Dependencies: 233
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5125 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- TOC entry 5126 (class 0 OID 0)
-- Dependencies: 217
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 21, true);


--
-- TOC entry 5127 (class 0 OID 0)
-- Dependencies: 235
-- Name: negocio_aperitivo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.negocio_aperitivo_id_seq', 1, true);


--
-- TOC entry 5128 (class 0 OID 0)
-- Dependencies: 249
-- Name: negocio_cita_aperitivos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.negocio_cita_aperitivos_id_seq', 1, false);


--
-- TOC entry 5129 (class 0 OID 0)
-- Dependencies: 247
-- Name: negocio_cita_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.negocio_cita_id_seq', 1, false);


--
-- TOC entry 5130 (class 0 OID 0)
-- Dependencies: 237
-- Name: negocio_colaborador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.negocio_colaborador_id_seq', 1, true);


--
-- TOC entry 5131 (class 0 OID 0)
-- Dependencies: 245
-- Name: negocio_historiaclinica_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.negocio_historiaclinica_id_seq', 1, false);


--
-- TOC entry 5132 (class 0 OID 0)
-- Dependencies: 239
-- Name: negocio_paciente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.negocio_paciente_id_seq', 1, false);


--
-- TOC entry 5133 (class 0 OID 0)
-- Dependencies: 241
-- Name: negocio_servicio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.negocio_servicio_id_seq', 1, false);


--
-- TOC entry 5134 (class 0 OID 0)
-- Dependencies: 251
-- Name: negocio_servicio_tratamientos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.negocio_servicio_tratamientos_id_seq', 1, false);


--
-- TOC entry 5135 (class 0 OID 0)
-- Dependencies: 243
-- Name: negocio_tratamiento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.negocio_tratamiento_id_seq', 1, false);


--
-- TOC entry 4846 (class 2606 OID 25127)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4851 (class 2606 OID 25058)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4854 (class 2606 OID 25027)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4848 (class 2606 OID 25019)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4841 (class 2606 OID 25049)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4843 (class 2606 OID 25013)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 25041)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4865 (class 2606 OID 25073)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4856 (class 2606 OID 25033)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 25047)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4871 (class 2606 OID 25087)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4859 (class 2606 OID 25122)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4874 (class 2606 OID 25108)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4836 (class 2606 OID 25007)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4838 (class 2606 OID 25005)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4834 (class 2606 OID 24999)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4912 (class 2606 OID 25255)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4877 (class 2606 OID 25134)
-- Name: negocio_aperitivo negocio_aperitivo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_aperitivo
    ADD CONSTRAINT negocio_aperitivo_pkey PRIMARY KEY (id);


--
-- TOC entry 4901 (class 2606 OID 25222)
-- Name: negocio_cita_aperitivos negocio_cita_aperitivos_cita_id_aperitivo_id_01f8f4fb_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_cita_aperitivos
    ADD CONSTRAINT negocio_cita_aperitivos_cita_id_aperitivo_id_01f8f4fb_uniq UNIQUE (cita_id, aperitivo_id);


--
-- TOC entry 4903 (class 2606 OID 25190)
-- Name: negocio_cita_aperitivos negocio_cita_aperitivos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_cita_aperitivos
    ADD CONSTRAINT negocio_cita_aperitivos_pkey PRIMARY KEY (id);


--
-- TOC entry 4896 (class 2606 OID 25184)
-- Name: negocio_cita negocio_cita_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_cita
    ADD CONSTRAINT negocio_cita_pkey PRIMARY KEY (id);


--
-- TOC entry 4880 (class 2606 OID 25142)
-- Name: negocio_colaborador negocio_colaborador_numero_documento_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_colaborador
    ADD CONSTRAINT negocio_colaborador_numero_documento_key UNIQUE (numero_documento);


--
-- TOC entry 4882 (class 2606 OID 25140)
-- Name: negocio_colaborador negocio_colaborador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_colaborador
    ADD CONSTRAINT negocio_colaborador_pkey PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 25176)
-- Name: negocio_historiaclinica negocio_historiaclinica_paciente_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_historiaclinica
    ADD CONSTRAINT negocio_historiaclinica_paciente_id_key UNIQUE (paciente_id);


--
-- TOC entry 4892 (class 2606 OID 25174)
-- Name: negocio_historiaclinica negocio_historiaclinica_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_historiaclinica
    ADD CONSTRAINT negocio_historiaclinica_pkey PRIMARY KEY (id);


--
-- TOC entry 4884 (class 2606 OID 25150)
-- Name: negocio_paciente negocio_paciente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_paciente
    ADD CONSTRAINT negocio_paciente_pkey PRIMARY KEY (id);


--
-- TOC entry 4886 (class 2606 OID 25157)
-- Name: negocio_servicio negocio_servicio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_servicio
    ADD CONSTRAINT negocio_servicio_pkey PRIMARY KEY (id);


--
-- TOC entry 4905 (class 2606 OID 25236)
-- Name: negocio_servicio_tratamientos negocio_servicio_tratami_servicio_id_tratamiento__caae94be_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_servicio_tratamientos
    ADD CONSTRAINT negocio_servicio_tratami_servicio_id_tratamiento__caae94be_uniq UNIQUE (servicio_id, tratamiento_id);


--
-- TOC entry 4907 (class 2606 OID 25196)
-- Name: negocio_servicio_tratamientos negocio_servicio_tratamientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_servicio_tratamientos
    ADD CONSTRAINT negocio_servicio_tratamientos_pkey PRIMARY KEY (id);


--
-- TOC entry 4888 (class 2606 OID 25166)
-- Name: negocio_tratamiento negocio_tratamiento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_tratamiento
    ADD CONSTRAINT negocio_tratamiento_pkey PRIMARY KEY (id);


--
-- TOC entry 4844 (class 1259 OID 25128)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4849 (class 1259 OID 25069)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4852 (class 1259 OID 25070)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4839 (class 1259 OID 25055)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4860 (class 1259 OID 25085)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4863 (class 1259 OID 25084)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4866 (class 1259 OID 25099)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4869 (class 1259 OID 25098)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4857 (class 1259 OID 25123)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4872 (class 1259 OID 25119)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4875 (class 1259 OID 25120)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4910 (class 1259 OID 25257)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4913 (class 1259 OID 25256)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4898 (class 1259 OID 25234)
-- Name: negocio_cita_aperitivos_aperitivo_id_b9ff512c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX negocio_cita_aperitivos_aperitivo_id_b9ff512c ON public.negocio_cita_aperitivos USING btree (aperitivo_id);


--
-- TOC entry 4899 (class 1259 OID 25233)
-- Name: negocio_cita_aperitivos_cita_id_318818cb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX negocio_cita_aperitivos_cita_id_318818cb ON public.negocio_cita_aperitivos USING btree (cita_id);


--
-- TOC entry 4893 (class 1259 OID 25218)
-- Name: negocio_cita_colaborador_id_9b6f2844; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX negocio_cita_colaborador_id_9b6f2844 ON public.negocio_cita USING btree (colaborador_id);


--
-- TOC entry 4894 (class 1259 OID 25219)
-- Name: negocio_cita_paciente_id_b8f866a6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX negocio_cita_paciente_id_b8f866a6 ON public.negocio_cita USING btree (paciente_id);


--
-- TOC entry 4897 (class 1259 OID 25220)
-- Name: negocio_cita_servicio_id_4c653b4a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX negocio_cita_servicio_id_4c653b4a ON public.negocio_cita USING btree (servicio_id);


--
-- TOC entry 4878 (class 1259 OID 25197)
-- Name: negocio_colaborador_numero_documento_350f73fc_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX negocio_colaborador_numero_documento_350f73fc_like ON public.negocio_colaborador USING btree (numero_documento varchar_pattern_ops);


--
-- TOC entry 4908 (class 1259 OID 25247)
-- Name: negocio_servicio_tratamientos_servicio_id_6f67e3f9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX negocio_servicio_tratamientos_servicio_id_6f67e3f9 ON public.negocio_servicio_tratamientos USING btree (servicio_id);


--
-- TOC entry 4909 (class 1259 OID 25248)
-- Name: negocio_servicio_tratamientos_tratamiento_id_b9956e2f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX negocio_servicio_tratamientos_tratamiento_id_b9956e2f ON public.negocio_servicio_tratamientos USING btree (tratamiento_id);


--
-- TOC entry 4915 (class 2606 OID 25064)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4916 (class 2606 OID 25059)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4914 (class 2606 OID 25050)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4917 (class 2606 OID 25079)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4918 (class 2606 OID 25074)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4919 (class 2606 OID 25093)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4920 (class 2606 OID 25088)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4921 (class 2606 OID 25109)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4922 (class 2606 OID 25114)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4927 (class 2606 OID 25228)
-- Name: negocio_cita_aperitivos negocio_cita_aperiti_aperitivo_id_b9ff512c_fk_negocio_a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_cita_aperitivos
    ADD CONSTRAINT negocio_cita_aperiti_aperitivo_id_b9ff512c_fk_negocio_a FOREIGN KEY (aperitivo_id) REFERENCES public.negocio_aperitivo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4928 (class 2606 OID 25223)
-- Name: negocio_cita_aperitivos negocio_cita_aperitivos_cita_id_318818cb_fk_negocio_cita_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_cita_aperitivos
    ADD CONSTRAINT negocio_cita_aperitivos_cita_id_318818cb_fk_negocio_cita_id FOREIGN KEY (cita_id) REFERENCES public.negocio_cita(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4924 (class 2606 OID 25203)
-- Name: negocio_cita negocio_cita_colaborador_id_9b6f2844_fk_negocio_colaborador_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_cita
    ADD CONSTRAINT negocio_cita_colaborador_id_9b6f2844_fk_negocio_colaborador_id FOREIGN KEY (colaborador_id) REFERENCES public.negocio_colaborador(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4925 (class 2606 OID 25208)
-- Name: negocio_cita negocio_cita_paciente_id_b8f866a6_fk_negocio_paciente_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_cita
    ADD CONSTRAINT negocio_cita_paciente_id_b8f866a6_fk_negocio_paciente_id FOREIGN KEY (paciente_id) REFERENCES public.negocio_paciente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4926 (class 2606 OID 25213)
-- Name: negocio_cita negocio_cita_servicio_id_4c653b4a_fk_negocio_servicio_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_cita
    ADD CONSTRAINT negocio_cita_servicio_id_4c653b4a_fk_negocio_servicio_id FOREIGN KEY (servicio_id) REFERENCES public.negocio_servicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4923 (class 2606 OID 25198)
-- Name: negocio_historiaclinica negocio_historiaclin_paciente_id_18d7388a_fk_negocio_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_historiaclinica
    ADD CONSTRAINT negocio_historiaclin_paciente_id_18d7388a_fk_negocio_p FOREIGN KEY (paciente_id) REFERENCES public.negocio_paciente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4929 (class 2606 OID 25237)
-- Name: negocio_servicio_tratamientos negocio_servicio_tra_servicio_id_6f67e3f9_fk_negocio_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_servicio_tratamientos
    ADD CONSTRAINT negocio_servicio_tra_servicio_id_6f67e3f9_fk_negocio_s FOREIGN KEY (servicio_id) REFERENCES public.negocio_servicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4930 (class 2606 OID 25242)
-- Name: negocio_servicio_tratamientos negocio_servicio_tra_tratamiento_id_b9956e2f_fk_negocio_t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.negocio_servicio_tratamientos
    ADD CONSTRAINT negocio_servicio_tra_tratamiento_id_b9956e2f_fk_negocio_t FOREIGN KEY (tratamiento_id) REFERENCES public.negocio_tratamiento(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-10-03 14:39:39

--
-- PostgreSQL database dump complete
--

\unrestrict v2OQbVSXRepWYdEjcQLdWyxSHT53irDRK5RFK2jb4wB17fSuly5DYREHJ1UWzbg

