# Generated by Django 5.2 on 2025-08-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_rename_etiquitas_pac_paciente_etiquetas_pac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='duracion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='extras',
            field=models.TextField(blank=True, null=True),
        ),
    ]
