# Generated by Django 6.0.7 on 2026-07-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_paciente_extras_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
