# Generated by Django 6.0.7 on 2026-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0006_add_activo_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('auth_key', models.CharField(max_length=255)),
                ('p256dh_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
