# Generated by Django 6.0.7 on 2026-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0007_add_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperitivo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
