# Generated by Django 6.0.7 on 2026-07-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0008_add_activo_to_aperitivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('REAL', 'Realizada'), ('CANC', 'Cancelada'), ('RETR', 'Atrasada')], default='PEND', max_length=4),
        ),
    ]
